"""create initial tables

Revision ID: a4f380f8e618
Revises: 
Create Date: 2026-05-06 16:18:01.821287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4f380f8e618'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wx_openid', sa.String(length=128), nullable=False),
    sa.Column('wx_unionid', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wx_openid'), 'users', ['wx_openid'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('legacy_cloud_id', sa.String(length=128), nullable=True),
    sa.Column('local_temp_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_normalized', sa.Text(), nullable=False),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('exam_scene', sa.String(length=64), nullable=True),
    sa.Column('exam_module', sa.String(length=64), nullable=True),
    sa.Column('understanding', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('analysis_level', sa.String(length=32), nullable=False),
    sa.Column('analysis_messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('understanding_source', sa.String(length=32), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('again_count', sa.Integer(), nullable=False),
    sa.Column('hard_count', sa.Integer(), nullable=False),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('easy_count', sa.Integer(), nullable=False),
    sa.Column('last_review_result', sa.String(length=32), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("analysis_level IN ('pass', 'warning', 'error')", name='ck_cards_analysis_level'),
    sa.CheckConstraint("analysis_status IN ('pending', 'done', 'failed')", name='ck_cards_analysis_status'),
    sa.CheckConstraint("card_type IN ('word', 'phrase', 'sentence')", name='ck_cards_card_type'),
    sa.CheckConstraint("status IN ('active', 'archived', 'deleted')", name='ck_cards_status'),
    sa.CheckConstraint("understanding_source IN ('local', 'machine', 'ai', 'user')", name='ck_cards_understanding_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'legacy_cloud_id', name='uq_cards_user_legacy_cloud_id'),
    sa.UniqueConstraint('user_id', 'local_temp_id', name='uq_cards_user_local_temp_id')
    )
    op.create_index('ix_cards_user_next_review_at', 'cards', ['user_id', 'next_review_at'], unique=False)
    op.create_index('ix_cards_user_status', 'cards', ['user_id', 'status'], unique=False)
    op.create_table('review_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name='ck_review_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_sessions_user_date_status', 'review_sessions', ['user_id', 'review_date', 'status'], unique=False)
    op.create_table('review_session_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('first_result', sa.String(length=32), nullable=True),
    sa.Column('final_result', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'done', 'skipped')", name='ck_review_session_items_status'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_review_session_items_session_position')
    )
    op.create_index('ix_review_session_items_session_status', 'review_session_items', ['session_id', 'status'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('session_item_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('result_label', sa.String(length=64), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('before_next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('after_next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('before_review_count', sa.Integer(), nullable=False),
    sa.Column('after_review_count', sa.Integer(), nullable=False),
    sa.Column('client_record_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("result IN ('again', 'hard', 'good', 'easy')", name='ck_review_records_result'),
    sa.CheckConstraint("source IN ('miniapp', 'retry', 'migration')", name='ck_review_records_source'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['session_item_id'], ['review_session_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_record_id', name='uq_review_records_user_client_record_id')
    )
    op.create_index('ix_review_records_card_reviewed_at', 'review_records', ['card_id', 'reviewed_at'], unique=False)
    op.create_index('ix_review_records_user_review_date', 'review_records', ['user_id', 'review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_records_user_review_date', table_name='review_records')
    op.drop_index('ix_review_records_card_reviewed_at', table_name='review_records')
    op.drop_table('review_records')
    op.drop_index('ix_review_session_items_session_status', table_name='review_session_items')
    op.drop_table('review_session_items')
    op.drop_index('ix_review_sessions_user_date_status', table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_index('ix_cards_user_status', table_name='cards')
    op.drop_index('ix_cards_user_next_review_at', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_wx_openid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
